# 对比的临时输出文件格式
diff_output = "csv"
# 合并的临时输出文件格式
merge_output = "txt"
# 对比工具的执行文件
compare_exe = "C:\\Program Files\\Beyond Compare 4\\BCompare.exe"
# 对比工具参数{left} {right}
diff_arg = "{left} {right}"
# 合并工具参数
merge_arg = "{remote} {local} {base} {output}"
# 对比历史记录数量
diff_history_count = 50