# 对比的临时输出文件格式
diff_output = "csv"
# 合并的临时输出文件格式
merge_output = "txt"
# 对比工具的执行文件
compare_exe = "D:\\software\\tools\\BeyondComparePro v4.1.5.21031 绿色精简优化版 x64\\Beyond Compare\\BCompare.exe"
# 对比工具参数{left} {right}
diff_arg = "{left} {right}"
# 合并工具参数
merge_arg = "{remote} {local} {base} {output}"